syntax = "proto3";
package demo;

import "google/api/annotations.proto";
import "google/protobuf/timestamp.proto";
import "google/protobuf/empty.proto";

import "types.proto";

option java_multiple_files = true;
option java_package = "com.matthews.poc.transcode.protos";
option java_outer_classname = "AddressProtos";

message Address {
  string name = 1;
  int32 id = 2;  // Unique ID number for this person.

  message Postal {
    string number = 1;
    string street = 2;
    string city = 3;
    string state = 4;
    string zip = 5;
    string country = 6;
  }

  Postal home = 4;

  google.protobuf.Timestamp last_updated = 5;
}
